# Generated by Django 4.1.6 on 2023-02-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme_support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deparments',
            name='last_update_at',
        ),
    ]
