# Generated by Django 4.1.6 on 2023-02-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_support', '0002_remove_deparments_last_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deparments',
            name='last_update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
