# Generated by Django 4.1.6 on 2023-02-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_support', '0003_deparments_last_update_at_user_last_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=220, unique=True)),
                ('body_description', models.CharField(max_length=220)),
                ('priority', models.CharField(max_length=220)),
                ('created_by', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
